#!/bin/bash

for file in $1_tests/*.py; do
    filename=$(basename "$file" .py)

    # Run the commands
    ./cnv $1 "$filename"
    echo "Python:"
    python3 $file

    echo -e "\nCC:"
    make -s run file="$filename"

    echo "========================================"
done
